{% set name = "mpmath" %}
{% set version = "1.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mpmath-{{ version }}.tar.gz
  sha256: 79ffb45cf9f4b101a807595bcb3e72e0396202e0b1d25d689134b48c4216a81a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
    - setuptools >=36.7.0
    - setuptools_scm >=1.7.0
  run:
    - python >=3

test:
  imports:
    - mpmath
    - mpmath.calculus
    - mpmath.functions
    - mpmath.libmp
    - mpmath.matrices
    - mpmath.tests

about:
  home: http://mpmath.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Python library for arbitrary-precision floating-point arithmetic
  description: |
    mpmath is a free Python library for real and complex floating-point
    arithmetic with arbitrary precision.
  doc_url: http://mpmath.org/doc/current/
  dev_url: https://github.com/fredrik-johansson/mpmath

extra:
  recipe-maintainers:
    - asmeurer
    - msarahan
    - ocefpaf
    - scopatz
