{% set name = "mpmath" %}
{% set version = "1.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mpmath-{{ version }}.tar.gz
  sha256: 7a28eb2a9774d00c7bc92411c19a89209d5da7c4c9a9e227be8330a23a25b91f

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation 

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=36.7.0
    - setuptools_scm >=1.7.0
  run:
    - python >={{ python_min }}

test:
  imports:
    - mpmath
    - mpmath.calculus
    - mpmath.functions
    - mpmath.libmp
    - mpmath.matrices
    - mpmath.tests
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://mpmath.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Python library for arbitrary-precision floating-point arithmetic
  description: |
    mpmath is a free Python library for real and complex floating-point
    arithmetic with arbitrary precision.
  doc_url: http://mpmath.org/doc/current/
  dev_url: https://github.com/fredrik-johansson/mpmath

extra:
  recipe-maintainers:
    - asmeurer
    - msarahan
    - ocefpaf
    - scopatz
