travis:
  secure:
    BINSTAR_TOKEN: lgEZMYpXUJqQk83k7Jzpvd4Hqo2Jka9M8ofvugBSaPCnl3KTW8VY9ba3c0U9qrwPJUKt662p9i+XVbvekUySBTnuy98xtkkF+xVRMxjJ1jrSPO70wqlireJ56VpwaR5Ir8hJ+5LituPmA3tjtN3XXHpsK5OKm2kKmr4of/nAhVhVeoUrQVhr/Lf32VMWkjqsW4ptSjLouZhrJruRHJLALlv1mOeRZFI/0kWL0S15Ij/3lFm9IN8UCPMCv+0EGdv1w/vva66Xix9yeTPbySfH7Ox5fr0R9ta8YBK7MYqdivq9wfyg4GDv5DD1EUCRsOJI6auB3a8nmga2/IFwrJB+8ofD908++4+DfDchEx4X7taZLoyo43MmtYQPKe1bTxCkXPNSEqQT2k0/zdlya7OJzKOULy/GAnfP1KlbJW+AsSWY7JNJ3j1FiGFkjnG4FiCeiOOZCZxhrmeeXklB9EuN/aSiX04nsNjLauJNX/Cv0SoKd7WO3wtQBh//aWFtbtTv1AEPKYgPyig+OIxbo2satrWHJWge0qvexyA9Ru2I/vVc9SqDHILYGhKG7KKoGN60UPSqBneJIA9vwTQ/AMPuBqhAjUlzCxWKz7p7IeY9ddhrPsAcRKoIdnYlU3RR7KKwxKEO+Ke9dkAiuPlH1cK1Ec96Kg6KNNSn5XnBIy0+0fw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
