travis:
  secure:
    BINSTAR_TOKEN: XkSGis7TtxerlAI6CpgdCAFxEphnaj56T6eIfsLvDK+awshdwYANArmOzfFgmLmxuVtaDD4Ch7cE+walTd/8akVzEU2SiMlSLfzkVCiLj3+1C3tT/OUYCD4OMoeEOszTjKWYitv+tR22jOXgK8F7Ud/f3gRYhmtnVd17Ig+zVAv2o1NMmcHgEWqTK8zd5iy8OL0SWjQjViuy4QXuSpKc+ox7C9Jl2Im84k4YQ6NExiTRp4jPFTUFLeByMNRNBLSfjSeLwJVkdl3vZ3I0tbyJS2m0g8xozUcHs3p6gv/QHJIah87EU+emysCytOHbcuh9BcTbBimWrxCqiauPJCeihPSSaaPde9TwzPRl1aeDkSIrYyoDY64Vkh8JuqDYNtBO3h37D7LBxfpLXHQAxaTlD6Ag5RBNRiblmK2nj/1Ah+LFmGOjZEC+ZqFtd0wDY4omsgPs2MZaaMQsQxSlMGhaN8K6Llto7aLjiXKd3U4d8XEh8AH+WxCGkcKt8cmg3M+Ejt0gODfJlZ4XXcfVynIGSPFDmWDUg/ruADhgjAfk8dyYl9VE1iSPdMOvD2ugE1a9sLiglazcURgaK2lnUURDseGgcTQi/+OlYWGrZdtNRXNf29qwwVBDiwvzJmhtxBnf6Q0Hivbfo9j04mIsuKmP+/s9rilG7bdxCYPKoaDda88=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
